#!/usr/bin/env node
// Auto-generated by release-creator (derived skill: release-market). Do not edit manually; regenerate via /release-creator-welcome.
'use strict';

const fs = require('fs');
const path = require('path');

const VERSION_REGEX = /^\d+\.\d+\.\d+$/;

function getVersionFiles(pluginName) {
  return [
    { path: `plugins/${pluginName}/.claude-plugin/plugin.json`, jsonPath: 'version' },
    { path: '.claude-plugin/marketplace.json', jsonPath: `plugins[name=${pluginName}].version` },
  ];
}

function resolveJsonPath(data, p) {
  return p.split('.').reduce((acc, seg) => {
    if (acc == null) return undefined;
    const m = seg.match(/^(\w+)\[(\w+)=([^\]]+)\]$/);
    if (m) {
      const arr = acc[m[1]];
      if (!Array.isArray(arr)) return undefined;
      return arr.find(x => x[m[2]] === m[3]);
    }
    return acc[seg];
  }, data);
}

function setJsonPath(data, p, value) {
  const parts = p.split('.');
  const last = parts.pop();
  const parent = parts.reduce((acc, seg) => {
    if (acc == null) return undefined;
    const m = seg.match(/^(\w+)\[(\w+)=([^\]]+)\]$/);
    if (m) {
      const arr = acc[m[1]];
      if (!Array.isArray(arr)) return undefined;
      return arr.find(x => x[m[2]] === m[3]);
    }
    return acc[seg];
  }, data);
  if (parent == null) throw new Error(`Cannot resolve parent path for: ${p}`);
  parent[last] = value;
}

function bump(cur, type) {
  if (VERSION_REGEX.test(type)) return type;
  const [a, b, c] = cur.split('.').map(Number);
  if (type === 'major') return `${a + 1}.0.0`;
  if (type === 'minor') return `${a}.${b + 1}.0`;
  if (type === 'patch') return `${a}.${b}.${c + 1}`;
  throw new Error(`Unknown bump type: ${type}. Use major, minor, patch, or a valid version string.`);
}

function main() {
  const pluginName = process.argv[2];
  const bumpType = process.argv[3] || 'patch';

  if (!pluginName) {
    console.error('Usage: node scripts/bump-version.cjs <plugin-name> <major|minor|patch|X.Y.Z>');
    console.error('  e.g. node scripts/bump-version.cjs token-reporter patch');
    process.exit(1);
  }

  const versionFiles = getVersionFiles(pluginName);

  const firstFilePath = path.resolve(versionFiles[0].path);
  if (!fs.existsSync(firstFilePath)) {
    console.error(`❌ Plugin "${pluginName}" not found: ${firstFilePath} does not exist.`);
    process.exit(1);
  }

  const firstData = JSON.parse(fs.readFileSync(firstFilePath, 'utf8'));
  const currentVersion = resolveJsonPath(firstData, versionFiles[0].jsonPath);
  if (!currentVersion || !VERSION_REGEX.test(currentVersion)) {
    console.error(`❌ Cannot read current version from ${versionFiles[0].path} (got: ${currentVersion})`);
    process.exit(1);
  }

  const nextVersion = bump(currentVersion, bumpType);
  if (!VERSION_REGEX.test(nextVersion)) {
    console.error(`❌ Invalid version: ${nextVersion}`);
    process.exit(1);
  }

  for (const f of versionFiles) {
    const filePath = path.resolve(f.path);
    if (!fs.existsSync(filePath)) {
      console.error(`❌ Mirror file not found: ${filePath}`);
      process.exit(1);
    }
    const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
    const resolved = resolveJsonPath(data, f.jsonPath);
    if (resolved === undefined) {
      console.error(`❌ Cannot resolve JSON path "${f.jsonPath}" in ${f.path}. Is the plugin registered?`);
      process.exit(1);
    }
    setJsonPath(data, f.jsonPath, nextVersion);
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
    console.log(`✅ ${f.path} → ${nextVersion}`);
  }

  console.log(nextVersion);
}

main();
