#!/usr/bin/env node
// Auto-generated by release-creator (derived skill: release-market). Do not edit manually.
//
// Usage:
//   node scripts/check-version.cjs <plugin-name>           # inline host (release checklist / manual)
//   node scripts/check-version.cjs <plugin-name> hook      # pre-push hook host
//
// 宿主差异：inline 查本地+远端 tag 并执行 bump-in-diff；
// hook 只查远端 tag 且跳过 bump-in-diff（push tag 时 HEAD 可能是 dist rebuild 等无 bump 的 commit）
'use strict';

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const VERSION_REGEX = /^\d+\.\d+\.\d+$/;

function getVersionFiles(pluginName) {
  return [
    { path: `plugins/${pluginName}/.claude-plugin/plugin.json`, jsonPath: 'version' },
    { path: '.claude-plugin/marketplace.json', jsonPath: `plugins[name=${pluginName}].version` },
  ];
}

function resolveJsonPath(data, p) {
  return p.split('.').reduce((acc, seg) => {
    if (acc == null) return undefined;
    const m = seg.match(/^(\w+)\[(\w+)=([^\]]+)\]$/);
    if (m) {
      const arr = acc[m[1]];
      if (!Array.isArray(arr)) return undefined;
      return arr.find(x => x[m[2]] === m[3]);
    }
    return acc[seg];
  }, data);
}

function readVersion(fileDef) {
  const filePath = path.resolve(fileDef.path);
  if (!fs.existsSync(filePath)) return undefined;
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  return resolveJsonPath(data, fileDef.jsonPath);
}

function checkMirrorConsistency(pluginName) {
  const files = getVersionFiles(pluginName);
  const versions = [];
  for (const f of files) {
    const v = readVersion(f);
    if (v === undefined) {
      console.error(`❌ mirror-consistency: cannot read version from ${f.path} (jsonPath: ${f.jsonPath})`);
      process.exit(1);
    }
    versions.push({ file: f.path, version: v });
  }
  const first = versions[0].version;
  for (const entry of versions) {
    if (entry.version !== first) {
      console.error(`❌ mirror-consistency: version mismatch`);
      for (const e of versions) console.error(`   ${e.file} → ${e.version}`);
      process.exit(1);
    }
  }
  console.log(`✅ mirror-consistency: ${first}`);
  return first;
}

function checkTagConflict(pluginName, version, host) {
  const tag = `${pluginName}-v${version}`;
  // inline 宿主（release checklist，本地 tag 还没创建）：查本地 + 远端
  // hook 宿主（pre-push，本地 tag 必然已创建——就是要 push 的对象）：只查远端
  if (host !== 'hook') {
    try {
      execSync(`git rev-parse ${tag}`, { stdio: 'pipe' });
      console.error(`❌ tag-conflict: local tag "${tag}" already exists`);
      process.exit(1);
    } catch {}
  }
  try {
    const remote = execSync(`git ls-remote --tags origin refs/tags/${tag}`, { encoding: 'utf8' });
    if (remote.trim()) {
      console.error(`❌ tag-conflict: remote tag "${tag}" already exists`);
      process.exit(1);
    }
  } catch {}
  console.log(`✅ tag-conflict: ${tag} is available`);
}

function checkWorkdirClean(pluginName) {
  const files = getVersionFiles(pluginName).map(f => f.path);
  const dirty = execSync('git status --porcelain -- ' + files.join(' '), { encoding: 'utf8' }).trim();
  if (dirty) {
    console.error(`❌ workdir-clean: version files have uncommitted changes:`);
    console.error(dirty);
    process.exit(1);
  }
  console.log(`✅ workdir-clean`);
}

function checkBumpInDiff(pluginName) {
  const files = getVersionFiles(pluginName).map(f => f.path);
  let changed;
  try {
    changed = execSync('git diff --name-only origin/main..HEAD', { encoding: 'utf8' });
  } catch {
    changed = execSync('git diff --name-only HEAD~1..HEAD', { encoding: 'utf8' });
  }
  for (const f of files) {
    if (changed.includes(f)) {
      console.log(`✅ bump-in-diff: ${f} modified`);
      return;
    }
  }
  console.error(`❌ bump-in-diff: no version file changes found in current diff`);
  process.exit(1);
}

function checkRegexCompliance(version) {
  if (!VERSION_REGEX.test(version)) {
    console.error(`❌ regex-compliance: "${version}" does not match ${VERSION_REGEX}`);
    process.exit(1);
  }
  console.log(`✅ regex-compliance: ${version}`);
}

function main() {
  const pluginName = process.argv[2];
  // host: 'hook' 或 'inline'（默认）—— 决定 tag-conflict 的分支以及是否跑 bump-in-diff
  const host = process.argv[3] === 'hook' ? 'hook' : 'inline';

  if (!pluginName) {
    console.error('Usage: node scripts/check-version.cjs <plugin-name> [hook|inline]');
    process.exit(1);
  }

  const pluginJsonPath = path.resolve(`plugins/${pluginName}/.claude-plugin/plugin.json`);
  if (!fs.existsSync(pluginJsonPath)) {
    console.error(`❌ Plugin "${pluginName}" not found: ${pluginJsonPath} does not exist.`);
    process.exit(1);
  }

  console.log(`\n▶ Checking ${pluginName} (host=${host})...\n`);

  const version = checkMirrorConsistency(pluginName);
  checkRegexCompliance(version);
  checkTagConflict(pluginName, version, host);
  checkWorkdirClean(pluginName);
  // bump-in-diff 只在 inline 宿主下有意义——hook 宿主的 HEAD 可能是 dist rebuild 等无 bump 的 commit
  if (host !== 'hook') {
    checkBumpInDiff(pluginName);
  }

  console.log(`\n✅ All checks passed for ${pluginName} v${version}\n`);
}

main();
